version: '3'
services:

  flyway:
    image: flyway/flyway:9.1
    container_name: flyway
    command: -url=jdbc:postgresql://postgres:5432/wisdom -schemas=public -user=keycloak -password=password -connectRetries=60 -connectRetriesInterval=2 migrate
    volumes:
      - ./data:/flyway/sql
    depends_on:
      - db 

  db:
    image: postgres
    container_name: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=wisdom
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-U", "keycloak"]
      interval: 5s
      timeout: 1s
      retries: 2